In [1]:
import torch
import numpy as np

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.FloatTensor(3, 4, 5)

In [3]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
z = x.reshape(6, 10) 
z

tensor([[6.3932e-37, 0.0000e+00, 9.1084e-44, 0.0000e+00, 6.3985e-37, 0.0000e+00,
         6.3985e-37, 0.0000e+00, 3.5733e-43, 0.0000e+00],
        [8.2677e-44, 0.0000e+00, 6.3985e-37, 0.0000e+00, 6.3985e-37, 0.0000e+00,
         3.5733e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.5733e-43, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 3.5733e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.5733e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 3.5733e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
y = np.array([1, 4, 2, 2, 1])
x * y

tensor([[[6.3932e-37, 0.0000e+00, 1.8217e-43, 0.0000e+00, 6.3985e-37],
         [0.0000e+00, 2.5594e-36, 0.0000e+00, 7.1466e-43, 0.0000e+00],
         [8.2677e-44, 0.0000e+00, 1.2797e-36, 0.0000e+00, 6.3985e-37],
         [0.0000e+00, 1.4293e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.5733e-43],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 7.1466e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[3.5733e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 7.1466e-43, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]],
       dtype=torch.float64)

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
z.matmul(z.clone().reshape(10, 6))

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75*t в точке (1, 0.5, 2)
x=torch.tensor(1.0, requires_grad=True) 
z=torch.tensor(0.5, requires_grad=True) 
t=torch.tensor(2.0, requires_grad=True) 
y = x**3 + z - 75*t 
y.backward() 
print(x.grad)
print(z.grad)
print(t.grad)

tensor(3.)
tensor(1.)
tensor(-75.)


In [8]:
# Создайте единичный тензор размера 5x6
x = torch.ones(5, 6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [9]:
# Переведите его в формат numpy
x = x.numpy()
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [10]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
